- type: roleLoadout
  id: JobSTTankCrew
  points: 7
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  # - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  # - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC
